"use client";
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Shield, Mail, ChevronRight, Home, FileText } from 'lucide-react';
import { ScrollArea } from "@/components/ui/scroll-area";

const SupportPolicy = () => {
  const sections = [
    { id: "introduction", title: "Introduction" },
    { id: "interpretation", title: "Interpretation and Definitions" },
    { id: "cancellation", title: "Your Order Cancellation Rights" }
  ];

  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    element?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="text-white py-12" style={{ backgroundColor: '#D3B750' }}>
        <div className="container mx-auto px-4">
          {/* Breadcrumb */}
          <div className="flex items-center space-x-2 mb-6" style={{ color: 'rgba(255, 255, 255, 0.9)' }}>
            <Home className="w-4 h-4" />
            <ChevronRight className="w-4 h-4" />
            <span>Support Policy</span>
          </div>
          
          <div className="flex items-center space-x-4">
            <Shield className="w-12 h-12" />
            <div>
              <h1 className="text-4xl font-bold mb-2">Support Policy</h1>
              <p className="text-xl" style={{ color: 'rgba(255, 255, 255, 0.9)' }}>
                Return and Refund Policy
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-4 py-12">
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
          {/* Table of Contents - Sidebar */}
          <div className="lg:col-span-1">
            <Card className="sticky top-8">
              <CardHeader>
                <CardTitle className="text-lg">Quick Navigation</CardTitle>
              </CardHeader>
              <CardContent>
                <ScrollArea className="h-96">
                  <nav className="space-y-2">
                    {sections.map((section, index) => (
                      <button
                        key={section.id}
                        onClick={() => scrollToSection(section.id)}
                        className="w-full text-left p-2 text-sm rounded-md transition-colors"
                        style={{ 
                          color: '#1f2937'
                        }}
                        onMouseEnter={(e) => {
                          e.currentTarget.style.backgroundColor = '#D3B7501A';
                          e.currentTarget.style.color = '#D3B750';
                        }}
                        onMouseLeave={(e) => {
                          e.currentTarget.style.backgroundColor = 'transparent';
                          e.currentTarget.style.color = '#1f2937';
                        }}
                      >
                        {index + 1}. {section.title}
                      </button>
                    ))}
                  </nav>
                </ScrollArea>
              </CardContent>
            </Card>
          </div>

          {/* Main Content */}
          <div className="lg:col-span-3 space-y-8">
            {/* Introduction */}
            <Card id="introduction">
              <CardHeader>
                <CardTitle className="text-2xl" style={{ color: '#D3B750' }}>Introduction</CardTitle>
              </CardHeader>
              <CardContent className="prose max-w-none">
                <div className="mb-4 p-4 rounded-md" style={{ backgroundColor: '#D3B7501A', borderLeft: '4px solid #D3B750' }}>
                  <p className="font-semibold" style={{ color: '#D3B750' }}>
                    Our Return and Refund Policy was last updated [Oct 2023]
                  </p>
                </div>
                <p className="text-lg text-muted-foreground leading-relaxed mb-4">
                  Thank you for shopping at <strong>Indrani Enterprises</strong>.
                </p>
                <p className="mb-4">
                  If, for any reason, You are not completely satisfied with a purchase We invite You to review our policy on refunds and returns. This Return and Refund Policy was generated by TermsFeed Return and Refund Policy Generator.
                </p>
                <p>
                  The following terms are applicable for any products that You purchased with Us.
                </p>
              </CardContent>
            </Card>

            {/* Interpretation and Definitions */}
            <Card id="interpretation">
              <CardHeader>
                <CardTitle className="text-xl" style={{ color: '#D3B750' }}>Interpretation and Definitions</CardTitle>
              </CardHeader>
              <CardContent className="prose max-w-none">
                <h4 className="font-semibold mt-4 mb-2">Interpretation</h4>
                <p>
                  The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>
                
                <h4 className="font-semibold mt-6 mb-2">Definitions</h4>
                <p className="mb-4">For the purposes of this Return and Refund Policy:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>"Company"</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to <strong>Indrani Enterprises</strong>.</li>
                  <li><strong>"Goods"</strong> refers to the items offered for sale on the Service.</li>
                  <li><strong>"Orders"</strong> means a request by You to purchase Goods from Us.</li>
                  <li><strong>"Service"</strong> refers to the Website.</li>
                  <li><strong>"Website"</strong> refers to <strong>Indrani Enterprises</strong>, accessible from <strong>https://www.indraniie.com/</strong></li>
                  <li><strong>"You"</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>
              </CardContent>
            </Card>

            {/* Your Order Cancellation Rights */}
            <Card id="cancellation">
              <CardHeader>
                <CardTitle className="text-xl" style={{ color: '#D3B750' }}>Your Order Cancellation Rights</CardTitle>
              </CardHeader>
              <CardContent className="prose max-w-none">
                <p className="mb-4">
                  Please refer to <a href="/returnpolicy" className="font-semibold" style={{ color: '#D3B750' }}>Return policy page</a>.
                </p>
                <p className="mb-4">
                  In order to exercise Your right of cancellation, You must inform Us of your decision by means of a clear statement. You can inform us of your decision by:
                </p>
                <ul className="list-disc pl-6 space-y-2 mb-4">
                  <li>By sending us an email: <a href="mailto:reachus@indraniie.com" className="font-semibold" style={{ color: '#D3B750' }}>reachus@indraniie.com</a></li>
                </ul>
                <div className="mt-6 p-4 rounded-md" style={{ backgroundColor: '#D3B7501A', borderLeft: '4px solid #D3B750' }}>
                  <p className="font-semibold mb-2" style={{ color: '#D3B750' }}>Reimbursement:</p>
                  <p>
                    We will reimburse You no later than 14 days from the day on which We receive the returned Goods. We will use the same means of payment as You used for the Order, and You will not incur any fees for such reimbursement.
                  </p>
                </div>
              </CardContent>
            </Card>

            {/* Contact Us */}
            <Card style={{ backgroundColor: '#D3B7501A', borderColor: '#D3B75033' }}>
              <CardHeader>
                <CardTitle className="text-xl" style={{ color: '#D3B750' }}>Contact Us</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="mb-4">
                  If you have any questions about this Support Policy, You can contact us:
                </p>
                <div className="flex flex-col sm:flex-row gap-4">
                  <Button 
                    asChild 
                    className="text-white"
                    style={{ backgroundColor: '#D3B750' }}
                    onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#B89A3F'}
                    onMouseLeave={(e) => e.currentTarget.style.backgroundColor = '#D3B750'}
                  >
                    <a href="mailto:reachus@indraniie.com">
                      <Mail className="w-4 h-4 mr-2" />
                      reachus@indraniie.com
                    </a>
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SupportPolicy;

